### ISSUE TITLE
Render color of veggie in a box next to the population of voter that it corresponds 

### ISSUE THREAD

**Issue by eliaswood** [timhaley94/election_simulator#3]
Would it be possible to in some way distinguish which color is for voter group? Is it implied that they are in the same order so from top to bottom of veggies is top to bottom of voters?

**Comment by timhaley94** [comment]
So the parties and the voter groups are different. The voter controls just tell you which percent of voters will use a "rational" strategy, and establishment strategy, etc., but some rational voters may voter for the 'corn' party or the 'turnip' party, etc.

I will say Laura was confused the same way by the graph, thinking that the voter groups were the same as parties. So perhaps there is a way in the body copy to emphasis the difference. The TODO item to add help text to each voting strategy may help because it would explain what each strategy does.

**Comment by timhaley94** [comment]
To turn this issue into something actionable. We would want a tiny '?' next to the names of the voting strategies, and when you over the icon, a tooltip appears with the appropriate copy.

"Rational" - "Voters with this strategy attempt to maximize their personal benefit based on which parties are reasonably capable of winning, according to previous results."
Establishment - "Voters with this strategy try to maximize the chance the ruling party wins."
Anti-establishment - "Voters with this strategy try to maximize the chance a party other than the ruling party wins."
Loyalist - "Voters with this strategy always vote for the party they, personally, most align with."
Random - "Voters with this strategy randomly cast their vote."
